# -*- coding: utf-8 -*-
"""script4_gestion_exceptions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16QtIJlAqHAV51dAFH_IihAAAwY0Zi9YJ

2) Création de fonction comportant des modules de gestions des exceptions
"""

import numpy as np

def polyn(x):
  entree_valide = False 
  premiere_iteration = True
  while not entree_valide: 
    if not premiere_iteration: 
      x = float(input("saisir une nouvelle valeur: "))
    if isinstance(x, str):
      print("L'argument ne peux pas être une chaine de caractère, veuillez entrer une nouvelle valeur") 
    elif np.iscomplex(x):
      print("L'argument ne peux pas être un nombre complexe, veuillez entrer une nouvelle valeur")
    elif x < 0: 
      print("L'argument ne peux pas être un nombre négatif, veuillez entrer une nouvelle valeur ")
    elif x > 1000000000: #On considère arbitrairement que 1000000000 comme étant la valeur maximale autorisée
      print("L'argument ne peux pas être un si grand nombre, veuillez entrer une nouvelle valeur")
    elif x < 0.01: #On considère arbitrairement que 0.01 comme étant un petit nombre 
      print ("L'argument ne peux pas être un si petit nombre, veuilliez entrer une nouvelle valeur")
    else: 
      entree_valide = True 
    if premiere_iteration:
      premiere_iteration = False

  return x**3 - 1.5 * x**2 - 6 * x + 5

polyn(10)

#La seule condition que je n'ai pas réussi à gérer est celle des chaines de caractère.