# -*- coding: utf-8 -*-
"""script2_factorielle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1phlfmvbVkzruNMRcumF-tYYLOTelBnWe

b) Implémenter la fonction factorielle (Approche récursive ou classique)
"""

#Forme récursive de la fonction
def factorielle(n):
  if n == 0:
    return 1
  return n * factorielle(n-1)

#Vérification 
factorielle(5)

