# -*- coding: utf-8 -*-
"""script3_fibonnaci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AqbLx-iyf8xndEnq2dX2uBmZXECDnPHM

3) Implémentater la suite de Fibonnaci
"""

def fibo(n):
  termes = [0, 1]
  for i in range(n-2):
    termes.append(termes[-1] + termes[-2])
  liste_termes = ""
  for item in termes:
    liste_termes += str(item) + " , "
  return liste_termes

terme = int(input("Entrez un nombre: "))
print(fibo(terme))