# -*- coding: utf-8 -*-
"""script1_polynomiale .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QqqTuQi-UV6t9oF6jXh7yfH0rK9r2zjI

**1) Création de fonction mathématique simple en Python:**

a) Implémentation fonction polynomiale
"""

def polyn(x):
  return x**3 - 1.5 * x**2 - 6 * x + 5

#Vérification
polyn(5)

"""b) Implémenter la fonction factorielle (Approche récursive ou classique)"""

#Forme récursive de la fonction
def factorielle(n):
  if n == 0:
    return 1
  return n * factorielle(n-1)

#Vérification 
factorielle(5)

"""3) Implémentater la suite de Fibonnaci

"""

def fibo(n):
  termes = [0, 1]
  for i in range(n-2):
    termes.append(termes[-1] + termes[-2])
  liste_termes = ""
  for item in termes:
    liste_termes += str(item) + " , "
  return liste_termes

terme = int(input("Entrez un nombre: "))
print(fibo(terme))

